Controllers films users
Andreyspb82/java-filmorate pull request #3
Opened 2023-05-24 11:02 UTC by Andreyspb82

2023-05-25 04:10 UTC, sergeymamonov requested changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

В тестах можно сделать проще. Можно в методе, который выполняется перед каждым тестом создать валидный фильм или пользователя. И в каждом тесте менять нужный параметр через сеттер на невалидное значение.

2023-05-25 04:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean validationFilm(Film film) {
Можно сделать void. Тогда и здесь будет меньше строк. И в местах, где вызывается, тоже можно отказаться от if и будет меньше кода. Если валидация где-то нарушится, то кинется ошибка и код дальше выполняться не будет.

2023-05-25 04:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int userId = 0;
private

2023-05-25 04:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<User> getUsers() {
Здесь действительно необходимо отдавать интерфейс Collection? Это достаточно общий интерфейс, то есть это может быть и массив и множество.

2023-05-25 04:10 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (validationUser(user)) {
Можно проще, отказаться от if и validationUser будет возвращать void.

2023-05-25 04:10 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController filmController;
Модификатор доступа.

2023-05-25 04:10 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                Film createFilm = filmController.createFilm(new Film(-1, "", "description",
Логика тестирования должна быть следующая, что мы выбираем один параметр, который не валидный. Остальные параметры объекта должны быть валидными. И мы получаем ответ об ошибке именно по тестируемому параметру. То есть чтобы остальные параметры не влияли на тестирование. Поэтому id = -1 здесь быть не должно.

2023-05-25 04:10 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                Film createFilm = filmController.createFilm(new Film(-1, "name", "Пятеро друзей" +
Сейчас не явно что хотелось сделать, можно нагляднее "a".repeat(нужное количество раз). Тестовые данные в тестах должны говорить сами за себя, какую верную или неверную информацию они несут.

2023-05-25 04:10 UTC, sergeymamonov requested changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

В тестах можно сделать проще. Можно в методе, который выполняется перед каждым тестом создать валидный фильм или пользователя. И в каждом тесте менять нужный параметр через сеттер на невалидное значение.

2023-05-26 13:19 UTC, Andreyspb82 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                Film createFilm = filmController.createFilm(new Film(-1, "", "description",
При создании объекта, id  теперь присваиваю null.  Если сделать конструктор без id, то я смогу пройти тесты при создании объекта конструктором без id но не могу пройти тесты postman.  Поэтому у меня конструктор со всеми параметрами, и id при создании null

2023-05-26 13:27 UTC, Andreyspb82 commented
Попытался сжать коммиты с одинаковыми названиями с помощью squash, но я там сильнее ошибся и у них оказалось 2 родителя.   Начал читать про reabase чтобы переименовать коммиты, но страшно сделать еще хуже.

2023-05-27 10:18 UTC, sergeymamonov approved these changes

2023-05-27 16:53 UTC, merged