Add database
Andreyspb82/java-filmorate pull request #5
Opened 2023-07-08 15:01 UTC by Andreyspb82

2023-07-09 13:26 UTC, sergeymamonov requested changes

2023-07-09 13:26 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(
Здесь выполняются запросы к БД в цикле. Это нехорошо. Во-первых, они будут выполняться последовательно, во-вторых, происходит пересылка по сети, а это долго. К примеру, 1 запросы, сотые доли секунды, и у нас тысяча раз выполняется цикл, получается уже десятки секунд. То есть нужно всегда избегать запросов к БД в циклах.

2023-07-09 13:26 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                jdbcTemplate.update(
Запросы к БД в цикле.

2023-07-09 13:26 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException re) {
Не нужно ловить RuntimeException, нужно ловить конкретную ошибку. К примеру, в коде будет ошибка программиста. Вы ее всегда будет отлавливать и возвращать пустой массив, как будто так и должно быть.

2023-07-09 13:26 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +
Так не нужно оставлять код. Он вроде бы как и есть, но не работоспособный. С этого спринта уже не нужно хранилище в памяти. Поэтому либо удалить хранилище в памяти, либо реализовать корректно.

2023-07-09 13:26 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +	email varchar not null unique,
Размер varchar необходимо ограничивать.

2023-07-09 18:38 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(
Переделал. Сделал проверку, что по запросу возвращается список. Если да, то возвращаю её, иначе возвращаю пустой список.

2023-07-09 18:39 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException re) {
Переделал. Сделал проверку, что по запросу возвращается список. Если да, то возвращаю его, иначе возвращаю пустой список.

2023-07-09 18:40 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                jdbcTemplate.update(
Переделал. Теперь в цикле собираю строку заброса к БД и уже один раз отправляю итоговую строку к БД

2023-07-09 18:40 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +
Удалил класс хранилища в памяти

2023-07-09 18:41 UTC, Andreyspb82 commented on src/main/resources/schema.sql
> +	email varchar not null unique,
Добавил ограничения размера для varchar

2023-07-10 08:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(sqlGenres);
Я бы только написал jdbcTemplate.update(sqlBuilder.toString());, чтобы не писать строку с созданием строки.

2023-07-10 08:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException re) {
Можно было посмотреть, какие ошибки может кинуть метод queryForObject и перехватывать именно эти ошибки.

2023-07-10 08:35 UTC, sergeymamonov approved these changes

2023-07-10 10:33 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(sqlGenres);
Спасибо, сделаю, получится аккуратнее.

2023-07-10 10:39 UTC, Andreyspb82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException re) {
Я не сообразил как это сделать.   Получение списка:
 `List<List<Film>> films = jdbcTemplate.query(sql, filmsRowMapper());`
обернуть в  tru catch?

2023-07-18 13:15 UTC, merged